SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK as A
JOIN AUTHOR as B ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES as C ON C.BOOK_ID = A.BOOK_ID
WHERE DATE_FORMAT(C.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY desc