SELECT
U.USER_ID,
U.NICKNAME,
CONCAT(CITY, ' ',STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
CONCAT('010-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS 전화번호
FROM (
    SELECT B.WRITER_ID 
    FROM USED_GOODS_BOARD AS B 
    GROUP BY B.WRITER_ID
    HAVING COUNT(*) >= 3
) AS D
JOIN USED_GOODS_USER AS U
ON D.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC