SELECT A.WRITER_ID, B.NICKNAME, SUM(A.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as A, USED_GOODS_USER as B
WHERE A.WRITER_ID = B.USER_ID and STATUS = 'DONE'
GROUP BY A.WRITER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY 3