SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y%m') BETWEEN '202208' AND '202211'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AND DATE_FORMAT(START_DATE, '%Y%m') BETWEEN '202208' AND '202211'
GROUP BY CAR_ID, MONTH
ORDER BY MONTH, CAR_ID DESC


# SELECT CAR_ID, COUNT(*)
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE DATE_FORMAT(START_DATE, '%Y%m') BETWEEN '202208' AND '202211'
#     GROUP BY CAR_ID
#     HAVING COUNT(*) >= 5