SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(
        CASE 
            WHEN LENGTH IS NOT NULL THEN LENGTH 
            ELSE 10 
        END
    ) >= 33
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE